services:
  web:
    build: .
    command: flask run --host 0.0.0.0 --port 5000
    hostname: weather-app
    ports:
    - 5000:5000
    volumes:
      - .:/app
  mongo:
    image: mongo:4.4.16
    hostname: weatherDB
    ports:
    - 27017:27017
    volumes:
      - ./db:/data/db
  client:
    build: .
    volumes:
      - .:/app
    command: python3 src/client.py